<?php

namespace AppBundle\Repository;

/**
 * HistoryServerPingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryServerPingRepository extends \Doctrine\ORM\EntityRepository
{
}
