<?php

namespace AppBundle\Repository;

/**
 * ServerPingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerPingRepository extends \Doctrine\ORM\EntityRepository
{
}
