<?php

namespace AppBundle\Repository;

/**
 * ServerBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
