<?php

namespace AppBundle\Repository;

/**
 * TestStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestStageRepository extends \Doctrine\ORM\EntityRepository
{
}
